name: Deploy to ArgoCD

on:
  push:
    branches:
      - dev
      - qa
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (ACR)
        run: az acr login --name metabank

      - name: Prepare Image Tag
        id: prepare-tag
        run: |
          TAG=$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated TAG: $TAG"

      - name: Build and Push Docker Image to Azure ACR
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            metabank.azurecr.io/metanet-msa-migration-be-java:latest
            metabank.azurecr.io/metanet-msa-migration-be-java:${{ env.TAG }}

      - name: Checkout ArgoCD Repository (Always use main)
        uses: actions/checkout@v3
        with:
          repository: Metanet-Signal-Platoon/ArgoCD-metabank
          token: ${{ secrets.GH_PAT }}
          ref: main
          fetch-depth: 0  

      - name: Set Environment Variables Based on Branch
        run: |
          BASE_DIR="argo-metanet-msa-migration-be-java-helm"
          echo "BASE_DIR=$BASE_DIR" >> $GITHUB_ENV

          # 브랜치별 values 파일 설정
          echo "VALUES_FILE=$BASE_DIR/values-${{ github.ref_name }}.yaml" >> $GITHUB_ENV
          echo "VALUE_FILE_NAME=values-${{ github.ref_name }}.yaml" >> $GITHUB_ENV

          # applicationset.yaml 경로 고정
          echo "APP_SET_FILE=$BASE_DIR/applicationset.yaml" >> $GITHUB_ENV

      - name: Update Image in Values File
        run: |
          echo "Updating image tag in ${{ env.VALUES_FILE }}"
          sed -i "s|tag: \".*\"|tag: \"${{ env.TAG }}\"|" "${{ env.VALUES_FILE }}"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git add "${{ env.VALUES_FILE }}"

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update image tag in ${{ env.VALUES_FILE }}"
            git push origin main
          fi

      - name: Apply ArgoCD ApplicationSet
        run: |
          kubectl apply -f argo-metanet-msa-migration-be-java-helm/applicationset.yaml

      - name: Sync ArgoCD Application
        run: |
          argocd app sync metanet-msa-migration-be-java-${{ github.ref_name }} --grpc-web
